# Generated by Django 4.1.6 on 2023-02-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='desription',
            new_name='description',
        ),
    ]
